# Generated by Django 2.2.4 on 2019-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('beverage', 'Beverage'), ('cocktail', 'Cocktails'), ('appetizers', 'Appetizers'), ('entrees', 'Entrees'), ('desserts', 'Desserts'), ('sides', 'Sides')], max_length=1)),
                ('ingredients_list', models.ManyToManyField(to='pos_app.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_list', models.ManyToManyField(to='pos_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=6)),
                ('transaction', models.ManyToManyField(to='pos_app.Transaction')),
            ],
        ),
    ]
