# Generated by Django 2.2.4 on 2019-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_name',
            field=models.ManyToManyField(to='pos_app.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beverage', 'Beverage'), ('cocktail', 'Cocktails'), ('appetizers', 'Appetizers'), ('entrees', 'Entrees'), ('desserts', 'Desserts'), ('sides', 'Sides')], max_length=100),
        ),
    ]
