# Generated by Django 2.2.4 on 2019-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_auto_20190817_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_list',
            field=models.ManyToManyField(to='pos_app.Ingredient'),
        ),
    ]
